# syntax=docker/dockerfile:1
# Dev image for local compose usage

ARG RUBY_VERSION=3.2.2
FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq \
    && apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./
RUN bundle install

CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
